./run_introgression.py --population-file simulations/exome_and_sites__h_0.5__seed_6977220333793.txt --exon-coordinates clean_data/exome_and_sites_exon_coordinates.txt --exonic-sites clean_data/admixture_array_coordinates_exonic.txt --nonexonic-sites clean_data/admixture_array_coordinates_nonexonic.txt --dominance-coef 0.5 --model gravel --recomb-map clean_data/exome_and_sites_recombination_map.txt --save-trajectories --output-prefix tests/dilution/longterm_dilution_1 --dilution 2.5e-5 55000 0 &
./run_introgression.py --population-file simulations/exome_and_sites__h_0.5__seed_6977220333793.txt --exon-coordinates clean_data/exome_and_sites_exon_coordinates.txt --exonic-sites clean_data/admixture_array_coordinates_exonic.txt --nonexonic-sites clean_data/admixture_array_coordinates_nonexonic.txt --dominance-coef 0.5 --model gravel --recomb-map clean_data/exome_and_sites_recombination_map.txt --save-trajectories --output-prefix tests/dilution/longterm_dilution_2 --dilution 2.5e-5 55000 0 &
./run_introgression.py --population-file simulations/exome_and_sites__h_0.5__seed_6977220333793.txt --exon-coordinates clean_data/exome_and_sites_exon_coordinates.txt --exonic-sites clean_data/admixture_array_coordinates_exonic.txt --nonexonic-sites clean_data/admixture_array_coordinates_nonexonic.txt --dominance-coef 0.5 --model gravel --recomb-map clean_data/exome_and_sites_recombination_map.txt --save-trajectories --output-prefix tests/dilution/longterm_dilution_3 --dilution 2.5e-5 55000 0 &
./run_introgression.py --population-file simulations/exome_and_sites__h_0.5__seed_6977220333793.txt --exon-coordinates clean_data/exome_and_sites_exon_coordinates.txt --exonic-sites clean_data/admixture_array_coordinates_exonic.txt --nonexonic-sites clean_data/admixture_array_coordinates_nonexonic.txt --dominance-coef 0.5 --model gravel --recomb-map clean_data/exome_and_sites_recombination_map.txt --save-trajectories --output-prefix tests/dilution/longterm_dilution_4 --dilution 2.5e-5 55000 0 &
./run_introgression.py --population-file simulations/exome_and_sites__h_0.5__seed_6977220333793.txt --exon-coordinates clean_data/exome_and_sites_exon_coordinates.txt --exonic-sites clean_data/admixture_array_coordinates_exonic.txt --nonexonic-sites clean_data/admixture_array_coordinates_nonexonic.txt --dominance-coef 0.5 --model gravel --recomb-map clean_data/exome_and_sites_recombination_map.txt --save-trajectories --output-prefix tests/dilution/longterm_dilution_5 --dilution 2.5e-5 55000 0 &
./run_introgression.py --population-file simulations/exome_and_sites__h_0.5__seed_6977220333793.txt --exon-coordinates clean_data/exome_and_sites_exon_coordinates.txt --exonic-sites clean_data/admixture_array_coordinates_exonic.txt --nonexonic-sites clean_data/admixture_array_coordinates_nonexonic.txt --dominance-coef 0.5 --model gravel --recomb-map clean_data/exome_and_sites_recombination_map.txt --save-trajectories --output-prefix tests/dilution/longterm_dilution_6 --dilution 2.5e-5 55000 0 &
./run_introgression.py --population-file simulations/exome_and_sites__h_0.5__seed_6977220333793.txt --exon-coordinates clean_data/exome_and_sites_exon_coordinates.txt --exonic-sites clean_data/admixture_array_coordinates_exonic.txt --nonexonic-sites clean_data/admixture_array_coordinates_nonexonic.txt --dominance-coef 0.5 --model gravel --recomb-map clean_data/exome_and_sites_recombination_map.txt --save-trajectories --output-prefix tests/dilution/longterm_dilution_7 --dilution 2.5e-5 55000 0 &
./run_introgression.py --population-file simulations/exome_and_sites__h_0.5__seed_6977220333793.txt --exon-coordinates clean_data/exome_and_sites_exon_coordinates.txt --exonic-sites clean_data/admixture_array_coordinates_exonic.txt --nonexonic-sites clean_data/admixture_array_coordinates_nonexonic.txt --dominance-coef 0.5 --model gravel --recomb-map clean_data/exome_and_sites_recombination_map.txt --save-trajectories --output-prefix tests/dilution/longterm_dilution_8 --dilution 2.5e-5 55000 0 &
./run_introgression.py --population-file simulations/exome_and_sites__h_0.5__seed_6977220333793.txt --exon-coordinates clean_data/exome_and_sites_exon_coordinates.txt --exonic-sites clean_data/admixture_array_coordinates_exonic.txt --nonexonic-sites clean_data/admixture_array_coordinates_nonexonic.txt --dominance-coef 0.5 --model gravel --recomb-map clean_data/exome_and_sites_recombination_map.txt --save-trajectories --output-prefix tests/dilution/longterm_dilution_9 --dilution 2.5e-5 55000 0 &
./run_introgression.py --population-file simulations/exome_and_sites__h_0.5__seed_6977220333793.txt --exon-coordinates clean_data/exome_and_sites_exon_coordinates.txt --exonic-sites clean_data/admixture_array_coordinates_exonic.txt --nonexonic-sites clean_data/admixture_array_coordinates_nonexonic.txt --dominance-coef 0.5 --model gravel --recomb-map clean_data/exome_and_sites_recombination_map.txt --save-trajectories --output-prefix tests/dilution/longterm_dilution_10 --dilution 2.5e-5 55000 0 &

./run_introgression.py --population-file simulations/exome_and_sites__h_0.5__seed_6977220333793.txt --exon-coordinates clean_data/exome_and_sites_exon_coordinates.txt --exonic-sites clean_data/admixture_array_coordinates_exonic.txt --nonexonic-sites clean_data/admixture_array_coordinates_nonexonic.txt --dominance-coef 0.5 --model gravel --recomb-map clean_data/exome_and_sites_recombination_map.txt --save-trajectories --output-prefix tests/dilution/shortterm_dilution_1 --dilution 0.2 10000 7000 &
./run_introgression.py --population-file simulations/exome_and_sites__h_0.5__seed_6977220333793.txt --exon-coordinates clean_data/exome_and_sites_exon_coordinates.txt --exonic-sites clean_data/admixture_array_coordinates_exonic.txt --nonexonic-sites clean_data/admixture_array_coordinates_nonexonic.txt --dominance-coef 0.5 --model gravel --recomb-map clean_data/exome_and_sites_recombination_map.txt --save-trajectories --output-prefix tests/dilution/shortterm_dilution_2 --dilution 0.2 10000 7000 &
./run_introgression.py --population-file simulations/exome_and_sites__h_0.5__seed_6977220333793.txt --exon-coordinates clean_data/exome_and_sites_exon_coordinates.txt --exonic-sites clean_data/admixture_array_coordinates_exonic.txt --nonexonic-sites clean_data/admixture_array_coordinates_nonexonic.txt --dominance-coef 0.5 --model gravel --recomb-map clean_data/exome_and_sites_recombination_map.txt --save-trajectories --output-prefix tests/dilution/shortterm_dilution_3 --dilution 0.2 10000 7000 &
./run_introgression.py --population-file simulations/exome_and_sites__h_0.5__seed_6977220333793.txt --exon-coordinates clean_data/exome_and_sites_exon_coordinates.txt --exonic-sites clean_data/admixture_array_coordinates_exonic.txt --nonexonic-sites clean_data/admixture_array_coordinates_nonexonic.txt --dominance-coef 0.5 --model gravel --recomb-map clean_data/exome_and_sites_recombination_map.txt --save-trajectories --output-prefix tests/dilution/shortterm_dilution_4 --dilution 0.2 10000 7000 &
./run_introgression.py --population-file simulations/exome_and_sites__h_0.5__seed_6977220333793.txt --exon-coordinates clean_data/exome_and_sites_exon_coordinates.txt --exonic-sites clean_data/admixture_array_coordinates_exonic.txt --nonexonic-sites clean_data/admixture_array_coordinates_nonexonic.txt --dominance-coef 0.5 --model gravel --recomb-map clean_data/exome_and_sites_recombination_map.txt --save-trajectories --output-prefix tests/dilution/shortterm_dilution_5 --dilution 0.2 10000 7000 &
./run_introgression.py --population-file simulations/exome_and_sites__h_0.5__seed_6977220333793.txt --exon-coordinates clean_data/exome_and_sites_exon_coordinates.txt --exonic-sites clean_data/admixture_array_coordinates_exonic.txt --nonexonic-sites clean_data/admixture_array_coordinates_nonexonic.txt --dominance-coef 0.5 --model gravel --recomb-map clean_data/exome_and_sites_recombination_map.txt --save-trajectories --output-prefix tests/dilution/shortterm_dilution_6 --dilution 0.2 10000 7000 &
./run_introgression.py --population-file simulations/exome_and_sites__h_0.5__seed_6977220333793.txt --exon-coordinates clean_data/exome_and_sites_exon_coordinates.txt --exonic-sites clean_data/admixture_array_coordinates_exonic.txt --nonexonic-sites clean_data/admixture_array_coordinates_nonexonic.txt --dominance-coef 0.5 --model gravel --recomb-map clean_data/exome_and_sites_recombination_map.txt --save-trajectories --output-prefix tests/dilution/shortterm_dilution_7 --dilution 0.2 10000 7000 &
./run_introgression.py --population-file simulations/exome_and_sites__h_0.5__seed_6977220333793.txt --exon-coordinates clean_data/exome_and_sites_exon_coordinates.txt --exonic-sites clean_data/admixture_array_coordinates_exonic.txt --nonexonic-sites clean_data/admixture_array_coordinates_nonexonic.txt --dominance-coef 0.5 --model gravel --recomb-map clean_data/exome_and_sites_recombination_map.txt --save-trajectories --output-prefix tests/dilution/shortterm_dilution_8 --dilution 0.2 10000 7000 &
./run_introgression.py --population-file simulations/exome_and_sites__h_0.5__seed_6977220333793.txt --exon-coordinates clean_data/exome_and_sites_exon_coordinates.txt --exonic-sites clean_data/admixture_array_coordinates_exonic.txt --nonexonic-sites clean_data/admixture_array_coordinates_nonexonic.txt --dominance-coef 0.5 --model gravel --recomb-map clean_data/exome_and_sites_recombination_map.txt --save-trajectories --output-prefix tests/dilution/shortterm_dilution_9 --dilution 0.2 10000 7000 &
./run_introgression.py --population-file simulations/exome_and_sites__h_0.5__seed_6977220333793.txt --exon-coordinates clean_data/exome_and_sites_exon_coordinates.txt --exonic-sites clean_data/admixture_array_coordinates_exonic.txt --nonexonic-sites clean_data/admixture_array_coordinates_nonexonic.txt --dominance-coef 0.5 --model gravel --recomb-map clean_data/exome_and_sites_recombination_map.txt --save-trajectories --output-prefix tests/dilution/shortterm_dilution_10 --dilution 0.2 10000 7000 &

./run_introgression.py --population-file simulations/exome_and_sites__h_0.5__seed_6977220333793.txt --exon-coordinates clean_data/exome_and_sites_exon_coordinates.txt --exonic-sites clean_data/admixture_array_coordinates_exonic.txt --nonexonic-sites clean_data/admixture_array_coordinates_nonexonic.txt --dominance-coef 0.5 --model gravel --recomb-map clean_data/exome_and_sites_recombination_map.txt --save-trajectories --output-prefix tests/dilution/control_1 &
./run_introgression.py --population-file simulations/exome_and_sites__h_0.5__seed_6977220333793.txt --exon-coordinates clean_data/exome_and_sites_exon_coordinates.txt --exonic-sites clean_data/admixture_array_coordinates_exonic.txt --nonexonic-sites clean_data/admixture_array_coordinates_nonexonic.txt --dominance-coef 0.5 --model gravel --recomb-map clean_data/exome_and_sites_recombination_map.txt --save-trajectories --output-prefix tests/dilution/control_2 &
./run_introgression.py --population-file simulations/exome_and_sites__h_0.5__seed_6977220333793.txt --exon-coordinates clean_data/exome_and_sites_exon_coordinates.txt --exonic-sites clean_data/admixture_array_coordinates_exonic.txt --nonexonic-sites clean_data/admixture_array_coordinates_nonexonic.txt --dominance-coef 0.5 --model gravel --recomb-map clean_data/exome_and_sites_recombination_map.txt --save-trajectories --output-prefix tests/dilution/control_3 &
./run_introgression.py --population-file simulations/exome_and_sites__h_0.5__seed_6977220333793.txt --exon-coordinates clean_data/exome_and_sites_exon_coordinates.txt --exonic-sites clean_data/admixture_array_coordinates_exonic.txt --nonexonic-sites clean_data/admixture_array_coordinates_nonexonic.txt --dominance-coef 0.5 --model gravel --recomb-map clean_data/exome_and_sites_recombination_map.txt --save-trajectories --output-prefix tests/dilution/control_4 &
./run_introgression.py --population-file simulations/exome_and_sites__h_0.5__seed_6977220333793.txt --exon-coordinates clean_data/exome_and_sites_exon_coordinates.txt --exonic-sites clean_data/admixture_array_coordinates_exonic.txt --nonexonic-sites clean_data/admixture_array_coordinates_nonexonic.txt --dominance-coef 0.5 --model gravel --recomb-map clean_data/exome_and_sites_recombination_map.txt --save-trajectories --output-prefix tests/dilution/control_5 &
./run_introgression.py --population-file simulations/exome_and_sites__h_0.5__seed_6977220333793.txt --exon-coordinates clean_data/exome_and_sites_exon_coordinates.txt --exonic-sites clean_data/admixture_array_coordinates_exonic.txt --nonexonic-sites clean_data/admixture_array_coordinates_nonexonic.txt --dominance-coef 0.5 --model gravel --recomb-map clean_data/exome_and_sites_recombination_map.txt --save-trajectories --output-prefix tests/dilution/control_6 &
./run_introgression.py --population-file simulations/exome_and_sites__h_0.5__seed_6977220333793.txt --exon-coordinates clean_data/exome_and_sites_exon_coordinates.txt --exonic-sites clean_data/admixture_array_coordinates_exonic.txt --nonexonic-sites clean_data/admixture_array_coordinates_nonexonic.txt --dominance-coef 0.5 --model gravel --recomb-map clean_data/exome_and_sites_recombination_map.txt --save-trajectories --output-prefix tests/dilution/control_7 &
./run_introgression.py --population-file simulations/exome_and_sites__h_0.5__seed_6977220333793.txt --exon-coordinates clean_data/exome_and_sites_exon_coordinates.txt --exonic-sites clean_data/admixture_array_coordinates_exonic.txt --nonexonic-sites clean_data/admixture_array_coordinates_nonexonic.txt --dominance-coef 0.5 --model gravel --recomb-map clean_data/exome_and_sites_recombination_map.txt --save-trajectories --output-prefix tests/dilution/control_8 &
./run_introgression.py --population-file simulations/exome_and_sites__h_0.5__seed_6977220333793.txt --exon-coordinates clean_data/exome_and_sites_exon_coordinates.txt --exonic-sites clean_data/admixture_array_coordinates_exonic.txt --nonexonic-sites clean_data/admixture_array_coordinates_nonexonic.txt --dominance-coef 0.5 --model gravel --recomb-map clean_data/exome_and_sites_recombination_map.txt --save-trajectories --output-prefix tests/dilution/control_9 &
./run_introgression.py --population-file simulations/exome_and_sites__h_0.5__seed_6977220333793.txt --exon-coordinates clean_data/exome_and_sites_exon_coordinates.txt --exonic-sites clean_data/admixture_array_coordinates_exonic.txt --nonexonic-sites clean_data/admixture_array_coordinates_nonexonic.txt --dominance-coef 0.5 --model gravel --recomb-map clean_data/exome_and_sites_recombination_map.txt --save-trajectories --output-prefix tests/dilution/control_10 &
