name: nea-over-time
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bioconductor-biomart=2.32.1
  - bioconductor-bsgenome.hsapiens.ucsc.hg19=1.4.0
  - bioconductor-genomicranges=1.30.3
  - bioconductor-iranges=2.12.0
  - bioconductor-rtracklayer=1.38.3
  - bioconductor-ggbio=1.26.0
  - pybedtools=0.7.10
  - pysam=0.14.1
  - r-data.table=1.10.4
  - jupyter=1.0.0
  - jupyterlab=0.32.1
  - matplotlib=2.1.1
  - pandas=0.22.0
  - python=3.6.3
  - r-devtools=1.13.5
  - r-essentials=3.4.1
  - r-ggbeeswarm=0.6.0
  - r-future=1.8.1
