library(tidyverse)
library(stringr)



# Reading output log files ====================================================


#' Read output log file from a qpF4ratio run.
#'
#' @param logfile Name of the output log file.
#'
#' @return Tibble object with the parsed results.
read_qpF4ratio <- function(logfile) {
    log_lines <- readLines(logfile)

    # extract the number of analyzed test populations/individuals
    # (corresponding to the number of rows of the results table)
    n_pops <- log_lines[which(str_detect(log_lines, "^nplist:"))] %>%
        str_extract("[0-9]+$") %>%
        as.integer

    # parse the lines of the results section and extract the names of
    # tested populations/individuals, estimated admixture proportions
    # alpha, std. errors and Z-score
    res_lines <- log_lines[(length(log_lines) - n_pops) : (length(log_lines) - 1)] %>%
        str_replace("result: ", "") %>%
        str_replace_all(":", "") %>%
        str_replace_all(" +", " ") %>%
        str_replace("^ ", "")

    res_df <- res_lines %>%
        paste(collapse="\n") %>%
        read_delim(delim=" ", col_names=FALSE) %>%
        setNames(c("A", "O", "X", "C", "A", "O", "B", "C", "alpha", "stderr", "z")) %>%
        .[c("A", "B", "X", "C", "O", "alpha", "stderr", "z")]

    res_df
}


#' Read output log file from a qpDstats run.
#'
#' @param logfile Name of the output log file.
#'
#' @return Tibble object with the parsed results.
read_qpDstat <- function(logfile) {
    log_lines <- readLines(logfile)

    # extract the number of analyzed population quadruples
    n_quads <- length(log_lines) - (which(str_detect(log_lines, "^nrows, ncols:"))) - 1

    # parse the lines of the results section and extract the names of
    # tested populations/individuals, estimated admixture proportions
    # alpha, std. errors and Z-score
    res_lines <- log_lines[(length(log_lines) - n_quads) : (length(log_lines) - 1)] %>%
        str_replace("result: ", "") %>%
        str_replace_all(" +", " ") %>%
        str_replace_all("^ | $", "")

    res_df <- res_lines %>%
        paste(collapse="\n") %>%
        read_delim(delim=" ", col_names=FALSE) %>%
        .[c(1:6, ncol(.) - 2, ncol(.) - 1, ncol(.))] %>% # remove column with "best" if present
        setNames(c("W", "X", "Y", "Z", "Dstat", "Zscore", "BABA", "ABBA", "n_snps"))

    res_df
}



# Generating "poplist" files ==================================================


#' Generate a file with population "constellations" for a qpF4ratio run.
#'
#' @description For details about the format of the population list
#'     file see documentation of the ADMIXTOOLS package.
#' 
#' @param X, A, B, C, O Population names, using the terminology of
#'     Patterson et al., 2012
#' @param file Path to the poplist file that will be generated.
create_qpF4ratio_pops <- function(X, A, B, C, O, file) {
    lines <- sprintf("%s %s : %s %s :: %s %s : %s %s", A, O, X, C, A, O, B, C)
    writeLines(lines, file)
}


#' Generate a file with population "constellations" for a qpF4ratio run.
#'
#' @description For details about the format of the population list
#'     file see documentation of the ADMIXTOOLS package.
#' 
#' @param X, A, B, C, O Population names, using the terminology of
#'     Patterson et al., 2012. It is possible to specify vectors of
#'     population identifiers as W, X, etc. That way, all possible
#'     combinations of specified W, X, Y and Z quadruples will be
#'     generated.
#' @param poplist List of populations. It will be saved as a file, one
#'     population per line.
#' @param file Path to the poplist file that will be generated.
create_Dstats_pops <- function(W=NULL, X=NULL, Y=NULL, Z=NULL, poplist=NULL, file) {    
    if (all(!is.null(c(W, X, Y, Z)))) { # individual populations were specified
        lines <- c()
        for (w in W) for (x in X) for (y in Y) for (z in Z) {
            lines <- c(lines, sprintf("%s %s %s %s", w, x, y, z))
        }
    } else if (!is.null(poplist)) { # a simple list of populations was specified
        lines <- poplist
    } else { # missing population information
        stop("Population identifiers must be specified")
    }
    
    writeLines(lines, file)
}



# Generating "param" files ====================================================


#' Generate a parameter file.
#' 
#' @param param_file Path to the parameter file generated by this
#'     function.
#' @param pops_file Populations file (qpDstats quadruples, Dstats
#'     population list, qpF4ratio populations, etc.).
#' @param eigenstrat_prefix Prefix of the geno/snp/ind files (can
#'     include the path). If specified, geno_file/snp_file/ind_file
#'     will be ignored.
#' @param geno_file Path to the genotype file.
#' @param snp_file Path to the snp file.
#' @param ind_file Path to the ind file.
#' @param badsnp_file SNP file with information about ignored sites.
#' @param f4mode Run Dstats with an "f4mode: YES" option, estimating
#'     just the f4?
create_param_file <- function(param_file, pops_file,
                              eigenstrat_prefix=NULL,
                              geno_file=NULL, snp_file=NULL, ind_file= NULL,
                              badsnp_file=NULL,
                              f4mode=FALSE) {
    if (!is.null(eigenstrat_prefix)) {
        geno_file <- paste0(eigenstrat_prefix, ".geno")
        snp_file <- paste0(eigenstrat_prefix, ".snp")
        ind_file <- paste0(eigenstrat_prefix, ".ind")
    }

    if (any(is.null(c(geno_file, snp_file, ind_file)))) {
        stop("Either the 'eigenstrat_prefix' or the paths to geno/snp/ind files must be specified")
    }

    writeLines(sprintf("genotypename: %s\nsnpname: %s\nindivname: %s\npopfilename: %s",
                       geno_file, snp_file, ind_file, poplist_file),
               con=param_file)

    if (!is.null(badsnp_file)) {
        write(sprintf("badsnpname: %s", badsnp_file), file=param_file, append=TRUE)
    }

    if (f4mode) {
        write("f4mode: YES", file=param_file, append=TRUE)
    }
}



# Running ADMIXTOOLS commands =================================================


#' Run a given ADMIXTOOLS command.
#'
#' @param tool Which ADMIXTOOLS command to run. At the moment, only
#'     qpDstats and qpF4ratio are supported.
#' @param param_file Path to the parameter file.
#' @param log_file Path to the output file. If NULL, output will be
#'     printed to stdout.
run_cmd <- function(cmd, param_file, log_file=NULL, admixtools_path="/Users/martin_petr/local/Admixtools/bin/") {
    if (!cmd %in% c("qpDstats", "qpF4ratio")) {
        stop("ADMIXTOOLS command '", cmd, "' is not supported or does not exist")
    }

    output <- ifelse(!is.null(log_file), paste(">", log_file), "")
 
    system(command=paste(file.path(admixtools_path, cmd),
                         "-p",
                         param_file,
                         output))
}


test_f4 <- function() {
    create_qpF4ratio_pops(
        X=c("French", "Sardinian", "Han", "Dai", "Stuttgart", "Oase1", "UstIshim"),
        A="Yoruba", B="Dinka", C="Altai", O="Chimp",
        file="tests/xxxtest.pop")
    create_param_file("tests/xxxtest.par", "tests/xxxtest.pop", "UPA.K.P.V1.3.2")
    run_cmd("qpF4ratio", "tests/xxxtest.par", log_file="tests/xxxtest.log")
}


test_dstats <- function() {
    create_qpF4ratio_poplist(
        X=c("French", "Sardinian", "Han", "Dai", "Stuttgart", "Oase1", "UstIshim"),
        A="Yoruba", B="Dinka", C="Altai", O="Chimp",
        file="tests/xxxtest.pop")
    create_param_file("tests/xxxtest.par", "tests/xxxtest.pop", "UPA.K.P.V1.3.2")
    run_cmd("qpF4ratio", "tests/xxxtest.par", log_file="tests/xxxtest.log")
}
