library(tidyverse)


##
## Exported functions ------------------------------------------------
##

##
## Parse the population section of the SLiM file into a data frame.
##
read_populations <- function(slim_file) {
    read_section_data(slim_file, "Populations") %>%
        read.table(text=., col.names=c("pop_id", "pop_size", "sex")) %>%
        as_tibble
}


##
## Parse the mutation section of the SLiM file into a data frame.
##
read_mutations <- function(slim_file, m, p, t=0) {
    read_section_data(slim_file, "Mutations") %>% # take all lines with mutations
        .[which(!is.na(str_match(., p)))] %>%     # take lines matching pop. origin
        .[which(!is.na(str_match(., m)))] %>%     # take lines matching mut. type
        read.table(text=., # after pre-filtering above convert lines to data frame
                   col.names=c("mut_id", "run_id", "mut_type",
                               "pos", "s", "h", "pop_origin",
                               "gen_origin", "freq")) %>%
        as_tibble %>%
        filter(gen_origin >= t)
}


##
## Helper functions --------------------------------------------------
##


SECTION_HEADERS <- c("Populations", "Mutations", "Individuals", "Genomes")


##
## Read SLiM output file generated by the sim.outputFull() method.
##
read_slim_file <- function(path) {
    readLines(path)
}


##
## Read the positions of the SLiM output file section headers
## used to break up the whole file into individual chunks
## (population description, mutations, individuals and genomes).
##
read_section_delims <- function(slim_file) {
    # get positions of the section headers
    section_pos <- c(which(slim_file %in% paste0(SECTION_HEADERS, ":")),
                       length(slim_file))

    # put information about starts/ends of individuals section
    # into a data frame
    tibble(section=SECTION_HEADERS,
           start=section_pos[-length(section_pos)] + 1,
           end=section_pos[-1] - 1)
}


##
## Get the subset of SLiM output file contents for a given section.
##
read_section_data <- function(slim_file, section_name) {
    if (! section_name %in% SECTION_HEADERS)
        stop("Invalid SLiM output section specified!")

    delims <- read_section_delims(slim_file)
    pos_in_file <- filter(delims, section == section_name)

    slim_file[pos_in_file$start:pos_in_file$end]
}


##
## Parse the individual section of the SLiM file into a data frame.
##
read_individuals <- function(slim_file) {
    read_section_data(slim_file, "Individuals") %>%
        read.table(text=., col.names=c("ind_id", "sex", "genome1_id", "genome2_id")) %>%
        as_tibble
}
