library(magrittr)
library(dplyr)
library(stringr)
library(ggplot2)


SECTION_HEADERS <- c("Populations", "Mutations", "Individuals", "Genomes")


##
## Read SLiM output file generated by the sim.outputFull() method.
##
read_slim_file <- function(path) {
    readLines(path)
}

##
## Read the positions of the SLiM output file section headers
## used to break up the whole file into individual chunks
## (population description, mutations, individuals and genomes).
##
read_section_delims <- function(slim_file) {
    # get positions of the section headers
    section_pos <- c(which(slim_file %in% paste0(SECTION_HEADERS, ":")),
                       length(slim_file))

    # put information about starts/ends of individuals section
    # into a data frame
    data.frame(section=SECTION_HEADERS,
               start=section_pos[-length(section_pos)] + 1,
               end=section_pos[-1] - 1)
}


##
## Get the subset of SLiM output file contents for a given section.
##
read_section_data <- function(slim_file, section_name) {
    if (! section_name %in% SECTION_HEADERS)
        stop("Invalid SLiM output section specified!")

    delims <- read_section_delims(slim_file)

    pos_in_file <- filter(delims, section == section_name)
    return(slim_file[pos_in_file$start:pos_in_file$end])
}


##
## Parse the population section of the SLiM file into a data frame.
##
read_populations <- function(slim_file) {
    read_section_data(slim_file, "Populations") %>%
        read.table(text=., col.names=c("pop_id", "pop_size", "sex"))
}


##
## Parse the mutation section of the SLiM file into a data frame.
##
read_mutations <- function(slim_file, m, p, t=0) {
    read_section_data(slim_file, "Mutations") %>%
        read.table(text=., col.names=c("mut_id", "run_id", "mut_type",
                                       "pos", "s", "h", "pop_origin",
                                       "gen_origin", "freq")) %>%
        filter(mut_type == m & pop_origin == p & gen_origin >= t)
}


##
## Parse the individual section of the SLiM file into a data frame.
##
read_individuals <- function(slim_file) {
    read_section_data(slim_file, "Individuals") %>%
        read.table(text=., col.names=c("ind_id", "sex", "genome1_id", "genome2_id"))
}


## ggplot(mut, aes(pop_origin, log_s, fill=pop_origin)) +
##     geom_violin() +
##     geom_hline(yintercept=log10(1/(2 * c(1000, 10000))), color=c("green", "red")) +
##     coord_flip() +
##     ylim(-1, -12)

## group_by(mut, pop_origin) %>% summarise(mean(s), median(s), max(s), min(s))
